### ISSUE TITLE
A larger deadzone doesn't smooth correctly

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [beejjorgensen/jsgamepad#1]
When I use a deadzone of 0.5, the joystick doesn't smooth correctly. If I have my joystick all the way out diagonally, it, doesn't show it as all the way out. Of course, in order to fix this, you'd have to calculate the circle, which would mean, you need to input both axes.

**Comment by beejjorgensen** [comment]
Good catch. Give the new one a try.

**Comment by ego-lay-atman-bay** [comment]
It work great. Thanks. Also, I noticed that the function code on the website doesn't have the deadzone parameter
![image](https://user-images.githubusercontent.com/70973578/173204461-d8d217e6-7481-47aa-87ea-b551905c4ba1.png)

**Comment by beejjorgensen** [comment]
D'oh! Thanks, fixed!

**Comment by ego-lay-atman-bay** [comment]
you're welcome
